/**
 * ISO 4217 currency table (List One, current as of 2026, plus fund codes,
 * precious metals, special codes and recently withdrawn codes).
 *
 * Exchange rates here are DEMONSTRATION values (approximate units per 1 USD)
 * used to seed the demo rate engine. They are not market data.
 *
 * Tuple: code, numeric, isoMinor (null = N.A.), name, symbol, position (p/s),
 *        demoPerUSD (null = no rate), region, countries ('|'-separated)
 */
import type { CurrencyDef, Region } from './types';

type Row = [string, string, number | null, string, string, 'p' | 's', number | null, Region, string];

const FIAT: Row[] = [
  ['AED', '784', 2, 'UAE Dirham', 'د.إ', 's', 3.6725, 'middle_east', 'United Arab Emirates'],
  ['AFN', '971', 2, 'Afghani', '؋', 's', 70.5, 'asia', 'Afghanistan'],
  ['ALL', '008', 2, 'Lek', 'L', 's', 85.9, 'europe', 'Albania'],
  ['AMD', '051', 2, 'Armenian Dram', '֏', 's', 386.4, 'asia', 'Armenia'],
  ['AOA', '973', 2, 'Kwanza', 'Kz', 's', 917, 'africa', 'Angola'],
  ['ARS', '032', 2, 'Argentine Peso', '$', 'p', 1365, 'americas', 'Argentina'],
  ['AUD', '036', 2, 'Australian Dollar', 'A$', 'p', 1.53, 'oceania', 'Australia|Christmas Island|Cocos (Keeling) Islands|Heard Island and McDonald Islands|Kiribati|Nauru|Norfolk Island|Tuvalu'],
  ['AWG', '533', 2, 'Aruban Florin', 'ƒ', 'p', 1.79, 'americas', 'Aruba'],
  ['AZN', '944', 2, 'Azerbaijan Manat', '₼', 's', 1.7, 'asia', 'Azerbaijan'],
  ['BAM', '977', 2, 'Convertible Mark', 'KM', 's', 1.67, 'europe', 'Bosnia and Herzegovina'],
  ['BBD', '052', 2, 'Barbados Dollar', 'Bds$', 'p', 2.0, 'americas', 'Barbados'],
  ['BDT', '050', 2, 'Taka', '৳', 'p', 122.1, 'asia', 'Bangladesh'],
  ['BHD', '048', 3, 'Bahraini Dinar', 'BD', 'p', 0.376, 'middle_east', 'Bahrain'],
  ['BIF', '108', 0, 'Burundi Franc', 'FBu', 's', 2955, 'africa', 'Burundi'],
  ['BMD', '060', 2, 'Bermudian Dollar', 'BD$', 'p', 1.0, 'americas', 'Bermuda'],
  ['BND', '096', 2, 'Brunei Dollar', 'B$', 'p', 1.29, 'asia', 'Brunei Darussalam'],
  ['BOB', '068', 2, 'Boliviano', 'Bs', 'p', 6.91, 'americas', 'Bolivia'],
  ['BRL', '986', 2, 'Brazilian Real', 'R$', 'p', 5.38, 'americas', 'Brazil'],
  ['BSD', '044', 2, 'Bahamian Dollar', 'B$', 'p', 1.0, 'americas', 'Bahamas'],
  ['BTN', '064', 2, 'Ngultrum', 'Nu.', 'p', 87.9, 'asia', 'Bhutan'],
  ['BWP', '072', 2, 'Pula', 'P', 'p', 13.4, 'africa', 'Botswana'],
  ['BYN', '933', 2, 'Belarusian Ruble', 'Br', 's', 3.27, 'europe', 'Belarus'],
  ['BZD', '084', 2, 'Belize Dollar', 'BZ$', 'p', 2.0, 'americas', 'Belize'],
  ['CAD', '124', 2, 'Canadian Dollar', 'C$', 'p', 1.385, 'americas', 'Canada'],
  ['CDF', '976', 2, 'Congolese Franc', 'FC', 's', 2860, 'africa', 'Democratic Republic of the Congo'],
  ['CHF', '756', 2, 'Swiss Franc', 'CHF', 'p', 0.80, 'europe', 'Switzerland|Liechtenstein'],
  ['CLP', '152', 0, 'Chilean Peso', '$', 'p', 955, 'americas', 'Chile'],
  ['CNY', '156', 2, 'Yuan Renminbi', '¥', 'p', 7.13, 'asia', 'China'],
  ['COP', '170', 2, 'Colombian Peso', '$', 'p', 3920, 'americas', 'Colombia'],
  ['CRC', '188', 2, 'Costa Rican Colon', '₡', 'p', 503, 'americas', 'Costa Rica'],
  ['CUP', '192', 2, 'Cuban Peso', '₱', 'p', 24.0, 'americas', 'Cuba'],
  ['CVE', '132', 2, 'Cabo Verde Escudo', 'Esc', 's', 94.2, 'africa', 'Cabo Verde'],
  ['CZK', '203', 2, 'Czech Koruna', 'Kč', 's', 20.9, 'europe', 'Czechia'],
  ['DJF', '262', 0, 'Djibouti Franc', 'Fdj', 's', 177.7, 'africa', 'Djibouti'],
  ['DKK', '208', 2, 'Danish Krone', 'kr', 's', 6.39, 'europe', 'Denmark|Faroe Islands|Greenland'],
  ['DOP', '214', 2, 'Dominican Peso', 'RD$', 'p', 63.4, 'americas', 'Dominican Republic'],
  ['DZD', '012', 2, 'Algerian Dinar', 'DA', 's', 130.3, 'africa', 'Algeria'],
  ['EGP', '818', 2, 'Egyptian Pound', 'E£', 'p', 48.2, 'africa', 'Egypt'],
  ['ERN', '232', 2, 'Nakfa', 'Nfk', 's', 15.0, 'africa', 'Eritrea'],
  ['ETB', '230', 2, 'Ethiopian Birr', 'Br', 's', 143.5, 'africa', 'Ethiopia'],
  ['EUR', '978', 2, 'Euro', '€', 'p', 0.857, 'europe', 'Austria|Belgium|Bulgaria|Croatia|Cyprus|Estonia|Finland|France|Germany|Greece|Ireland|Italy|Latvia|Lithuania|Luxembourg|Malta|Netherlands|Portugal|Slovakia|Slovenia|Spain|Andorra|Monaco|San Marino|Vatican City|Montenegro|Kosovo|French Guiana|Guadeloupe|Martinique|Mayotte|Réunion|Saint Barthélemy|Saint Martin|Saint Pierre and Miquelon|Åland Islands'],
  ['FJD', '242', 2, 'Fiji Dollar', 'FJ$', 'p', 2.27, 'oceania', 'Fiji'],
  ['FKP', '238', 2, 'Falkland Islands Pound', '£', 'p', 0.745, 'americas', 'Falkland Islands'],
  ['GBP', '826', 2, 'Pound Sterling', '£', 'p', 0.745, 'europe', 'United Kingdom|Isle of Man|Jersey|Guernsey'],
  ['GEL', '981', 2, 'Lari', '₾', 's', 2.70, 'asia', 'Georgia'],
  ['GHS', '936', 2, 'Ghana Cedi', 'GH₵', 'p', 12.1, 'africa', 'Ghana'],
  ['GIP', '292', 2, 'Gibraltar Pound', '£', 'p', 0.745, 'europe', 'Gibraltar'],
  ['GMD', '270', 2, 'Dalasi', 'D', 's', 72.5, 'africa', 'Gambia'],
  ['GNF', '324', 0, 'Guinean Franc', 'FG', 's', 8670, 'africa', 'Guinea'],
  ['GTQ', '320', 2, 'Quetzal', 'Q', 'p', 7.66, 'americas', 'Guatemala'],
  ['GYD', '328', 2, 'Guyana Dollar', 'G$', 'p', 209.2, 'americas', 'Guyana'],
  ['HKD', '344', 2, 'Hong Kong Dollar', 'HK$', 'p', 7.79, 'asia', 'Hong Kong'],
  ['HNL', '340', 2, 'Lempira', 'L', 'p', 26.2, 'americas', 'Honduras'],
  ['HTG', '332', 2, 'Gourde', 'G', 'p', 131.0, 'americas', 'Haiti'],
  ['HUF', '348', 2, 'Forint', 'Ft', 's', 333, 'europe', 'Hungary'],
  ['IDR', '360', 2, 'Rupiah', 'Rp', 'p', 16550, 'asia', 'Indonesia'],
  ['ILS', '376', 2, 'New Israeli Sheqel', '₪', 'p', 3.33, 'middle_east', 'Israel'],
  ['INR', '356', 2, 'Indian Rupee', '₹', 'p', 88.6, 'asia', 'India|Bhutan'],
  ['IQD', '368', 3, 'Iraqi Dinar', 'ID', 's', 1310, 'middle_east', 'Iraq'],
  ['IRR', '364', 2, 'Iranian Rial', '﷼', 's', 42100, 'middle_east', 'Iran'],
  ['ISK', '352', 0, 'Iceland Krona', 'kr', 's', 122.5, 'europe', 'Iceland'],
  ['JMD', '388', 2, 'Jamaican Dollar', 'J$', 'p', 160.4, 'americas', 'Jamaica'],
  ['JOD', '400', 3, 'Jordanian Dinar', 'JD', 'p', 0.709, 'middle_east', 'Jordan'],
  ['JPY', '392', 0, 'Yen', '¥', 'p', 148.6, 'asia', 'Japan'],
  ['KES', '404', 2, 'Kenyan Shilling', 'KSh', 'p', 129.2, 'africa', 'Kenya'],
  ['KGS', '417', 2, 'Som', 'сом', 's', 87.4, 'asia', 'Kyrgyzstan'],
  ['KHR', '116', 2, 'Riel', '៛', 's', 4015, 'asia', 'Cambodia'],
  ['KMF', '174', 0, 'Comorian Franc', 'CF', 's', 421, 'africa', 'Comoros'],
  ['KPW', '408', 2, 'North Korean Won', '₩', 'p', 900, 'asia', 'Democratic People’s Republic of Korea'],
  ['KRW', '410', 0, 'Won', '₩', 'p', 1395, 'asia', 'Republic of Korea'],
  ['KWD', '414', 3, 'Kuwaiti Dinar', 'KD', 'p', 0.305, 'middle_east', 'Kuwait'],
  ['KYD', '136', 2, 'Cayman Islands Dollar', 'CI$', 'p', 0.833, 'americas', 'Cayman Islands'],
  ['KZT', '398', 2, 'Tenge', '₸', 's', 541, 'asia', 'Kazakhstan'],
  ['LAK', '418', 2, 'Lao Kip', '₭', 's', 21650, 'asia', 'Lao People’s Democratic Republic'],
  ['LBP', '422', 2, 'Lebanese Pound', 'LL', 's', 89500, 'middle_east', 'Lebanon'],
  ['LKR', '144', 2, 'Sri Lanka Rupee', 'Rs', 'p', 302, 'asia', 'Sri Lanka'],
  ['LRD', '430', 2, 'Liberian Dollar', 'L$', 'p', 180, 'africa', 'Liberia'],
  ['LSL', '426', 2, 'Loti', 'L', 'p', 17.5, 'africa', 'Lesotho'],
  ['LYD', '434', 3, 'Libyan Dinar', 'LD', 'p', 5.42, 'africa', 'Libya'],
  ['MAD', '504', 2, 'Moroccan Dirham', 'DH', 's', 9.08, 'africa', 'Morocco|Western Sahara'],
  ['MDL', '498', 2, 'Moldovan Leu', 'L', 's', 16.8, 'europe', 'Moldova'],
  ['MGA', '969', 2, 'Malagasy Ariary', 'Ar', 's', 4460, 'africa', 'Madagascar'],
  ['MKD', '807', 2, 'Denar', 'ден', 's', 52.8, 'europe', 'North Macedonia'],
  ['MMK', '104', 2, 'Kyat', 'K', 's', 2100, 'asia', 'Myanmar'],
  ['MNT', '496', 2, 'Tugrik', '₮', 's', 3595, 'asia', 'Mongolia'],
  ['MOP', '446', 2, 'Pataca', 'MOP$', 'p', 8.03, 'asia', 'Macao'],
  ['MRU', '929', 2, 'Ouguiya', 'UM', 's', 39.9, 'africa', 'Mauritania'],
  ['MUR', '480', 2, 'Mauritius Rupee', '₨', 'p', 45.6, 'africa', 'Mauritius'],
  ['MVR', '462', 2, 'Rufiyaa', 'Rf', 'p', 15.4, 'asia', 'Maldives'],
  ['MWK', '454', 2, 'Malawi Kwacha', 'MK', 'p', 1736, 'africa', 'Malawi'],
  ['MXN', '484', 2, 'Mexican Peso', 'Mex$', 'p', 18.4, 'americas', 'Mexico'],
  ['MYR', '458', 2, 'Malaysian Ringgit', 'RM', 'p', 4.21, 'asia', 'Malaysia'],
  ['MZN', '943', 2, 'Mozambique Metical', 'MT', 's', 63.9, 'africa', 'Mozambique'],
  ['NAD', '516', 2, 'Namibia Dollar', 'N$', 'p', 17.5, 'africa', 'Namibia'],
  ['NGN', '566', 2, 'Naira', '₦', 'p', 1520, 'africa', 'Nigeria'],
  ['NIO', '558', 2, 'Cordoba Oro', 'C$', 'p', 36.8, 'americas', 'Nicaragua'],
  ['NOK', '578', 2, 'Norwegian Krone', 'kr', 's', 10.0, 'europe', 'Norway|Svalbard and Jan Mayen|Bouvet Island'],
  ['NPR', '524', 2, 'Nepalese Rupee', 'Rs', 'p', 141.7, 'asia', 'Nepal'],
  ['NZD', '554', 2, 'New Zealand Dollar', 'NZ$', 'p', 1.71, 'oceania', 'New Zealand|Cook Islands|Niue|Pitcairn|Tokelau'],
  ['OMR', '512', 3, 'Rial Omani', 'RO', 'p', 0.3845, 'middle_east', 'Oman'],
  ['PAB', '590', 2, 'Balboa', 'B/.', 'p', 1.0, 'americas', 'Panama'],
  ['PEN', '604', 2, 'Sol', 'S/', 'p', 3.52, 'americas', 'Peru'],
  ['PGK', '598', 2, 'Kina', 'K', 'p', 4.12, 'oceania', 'Papua New Guinea'],
  ['PHP', '608', 2, 'Philippine Peso', '₱', 'p', 57.4, 'asia', 'Philippines'],
  ['PKR', '586', 2, 'Pakistan Rupee', 'Rs', 'p', 281.5, 'asia', 'Pakistan'],
  ['PLN', '985', 2, 'Zloty', 'zł', 's', 3.64, 'europe', 'Poland'],
  ['PYG', '600', 0, 'Guarani', '₲', 'p', 7280, 'americas', 'Paraguay'],
  ['QAR', '634', 2, 'Qatari Rial', 'QR', 'p', 3.64, 'middle_east', 'Qatar'],
  ['RON', '946', 2, 'Romanian Leu', 'lei', 's', 4.36, 'europe', 'Romania'],
  ['RSD', '941', 2, 'Serbian Dinar', 'дин.', 's', 100.4, 'europe', 'Serbia'],
  ['RUB', '643', 2, 'Russian Ruble', '₽', 's', 81.6, 'europe', 'Russian Federation'],
  ['RWF', '646', 0, 'Rwanda Franc', 'FRw', 's', 1445, 'africa', 'Rwanda'],
  ['SAR', '682', 2, 'Saudi Riyal', 'SR', 'p', 3.75, 'middle_east', 'Saudi Arabia'],
  ['SBD', '090', 2, 'Solomon Islands Dollar', 'SI$', 'p', 8.22, 'oceania', 'Solomon Islands'],
  ['SCR', '690', 2, 'Seychelles Rupee', 'SRe', 'p', 14.3, 'africa', 'Seychelles'],
  ['SDG', '938', 2, 'Sudanese Pound', '£SD', 'p', 601, 'africa', 'Sudan'],
  ['SEK', '752', 2, 'Swedish Krona', 'kr', 's', 9.42, 'europe', 'Sweden'],
  ['SGD', '702', 2, 'Singapore Dollar', 'S$', 'p', 1.29, 'asia', 'Singapore'],
  ['SHP', '654', 2, 'Saint Helena Pound', '£', 'p', 0.745, 'africa', 'Saint Helena, Ascension and Tristan da Cunha'],
  ['SLE', '925', 2, 'Leone', 'Le', 'p', 22.8, 'africa', 'Sierra Leone'],
  ['SOS', '706', 2, 'Somali Shilling', 'Sh.So.', 'p', 571, 'africa', 'Somalia'],
  ['SRD', '968', 2, 'Surinam Dollar', 'Sr$', 'p', 38.6, 'americas', 'Suriname'],
  ['SSP', '728', 2, 'South Sudanese Pound', 'SSP', 'p', 4560, 'africa', 'South Sudan'],
  ['STN', '930', 2, 'Dobra', 'Db', 's', 21.0, 'africa', 'Sao Tome and Principe'],
  ['SVC', '222', 2, 'El Salvador Colon', '₡', 'p', 8.75, 'americas', 'El Salvador'],
  ['SYP', '760', 2, 'Syrian Pound', 'LS', 's', 13000, 'middle_east', 'Syrian Arab Republic'],
  ['SZL', '748', 2, 'Lilangeni', 'E', 'p', 17.5, 'africa', 'Eswatini'],
  ['THB', '764', 2, 'Baht', '฿', 'p', 32.3, 'asia', 'Thailand'],
  ['TJS', '972', 2, 'Somoni', 'SM', 's', 9.45, 'asia', 'Tajikistan'],
  ['TMT', '934', 2, 'Turkmenistan New Manat', 'm', 's', 3.5, 'asia', 'Turkmenistan'],
  ['TND', '788', 3, 'Tunisian Dinar', 'DT', 's', 2.92, 'africa', 'Tunisia'],
  ['TOP', '776', 2, 'Pa’anga', 'T$', 'p', 2.38, 'oceania', 'Tonga'],
  ['TRY', '949', 2, 'Turkish Lira', '₺', 'p', 41.6, 'europe', 'Türkiye'],
  ['TTD', '780', 2, 'Trinidad and Tobago Dollar', 'TT$', 'p', 6.78, 'americas', 'Trinidad and Tobago'],
  ['TWD', '901', 2, 'New Taiwan Dollar', 'NT$', 'p', 30.4, 'asia', 'Taiwan'],
  ['TZS', '834', 2, 'Tanzanian Shilling', 'TSh', 'p', 2465, 'africa', 'Tanzania'],
  ['UAH', '980', 2, 'Hryvnia', '₴', 's', 41.3, 'europe', 'Ukraine'],
  ['UGX', '800', 0, 'Uganda Shilling', 'USh', 'p', 3490, 'africa', 'Uganda'],
  ['USD', '840', 2, 'US Dollar', '$', 'p', 1.0, 'americas', 'United States of America|Ecuador|El Salvador|Timor-Leste|Marshall Islands|Micronesia|Palau|Puerto Rico|Guam|American Samoa|Northern Mariana Islands|British Virgin Islands|Turks and Caicos Islands|Bonaire, Sint Eustatius and Saba|British Indian Ocean Territory|US Virgin Islands|United States Minor Outlying Islands'],
  ['UYU', '858', 2, 'Peso Uruguayo', '$U', 'p', 40.1, 'americas', 'Uruguay'],
  ['UZS', '860', 2, 'Uzbekistan Sum', 'soʻm', 's', 12050, 'asia', 'Uzbekistan'],
  ['VED', '926', 2, 'Bolívar Soberano (digital)', 'Bs.D', 'p', 175, 'americas', 'Venezuela'],
  ['VES', '928', 2, 'Bolívar Soberano', 'Bs.S', 'p', 175, 'americas', 'Venezuela'],
  ['VND', '704', 0, 'Dong', '₫', 's', 26250, 'asia', 'Viet Nam'],
  ['VUV', '548', 0, 'Vatu', 'VT', 's', 120, 'oceania', 'Vanuatu'],
  ['WST', '882', 2, 'Tala', 'WS$', 'p', 2.76, 'oceania', 'Samoa'],
  ['XAF', '950', 0, 'CFA Franc BEAC', 'FCFA', 's', 562, 'africa', 'Cameroon|Central African Republic|Chad|Congo|Equatorial Guinea|Gabon'],
  ['XCD', '951', 2, 'East Caribbean Dollar', 'EC$', 'p', 2.70, 'americas', 'Anguilla|Antigua and Barbuda|Dominica|Grenada|Montserrat|Saint Kitts and Nevis|Saint Lucia|Saint Vincent and the Grenadines'],
  ['XCG', '532', 2, 'Caribbean Guilder', 'Cg', 'p', 1.79, 'americas', 'Curaçao|Sint Maarten'],
  ['XOF', '952', 0, 'CFA Franc BCEAO', 'CFA', 's', 562, 'africa', 'Benin|Burkina Faso|Côte d’Ivoire|Guinea-Bissau|Mali|Niger|Senegal|Togo'],
  ['XPF', '953', 0, 'CFP Franc', '₣', 's', 102.3, 'oceania', 'French Polynesia|New Caledonia|Wallis and Futuna'],
  ['YER', '886', 2, 'Yemeni Rial', '﷼', 's', 239, 'middle_east', 'Yemen'],
  ['ZAR', '710', 2, 'Rand', 'R', 'p', 17.5, 'africa', 'South Africa|Lesotho|Namibia'],
  ['ZMW', '967', 2, 'Zambian Kwacha', 'ZK', 'p', 23.6, 'africa', 'Zambia'],
  ['ZWG', '924', 2, 'Zimbabwe Gold', 'ZiG', 'p', 26.8, 'africa', 'Zimbabwe'],
];

/** Fund codes (ISO 4217 "funds") — quoted, not used for everyday payments. */
const FUNDS: Row[] = [
  ['BOV', '984', 2, 'Mvdol', 'BOV', 'p', 0.42, 'americas', 'Bolivia'],
  ['CHE', '947', 2, 'WIR Euro', 'CHE', 'p', 0.857, 'europe', 'Switzerland'],
  ['CHW', '948', 2, 'WIR Franc', 'CHW', 'p', 0.80, 'europe', 'Switzerland'],
  ['CLF', '990', 4, 'Unidad de Fomento', 'UF', 'p', 0.0244, 'americas', 'Chile'],
  ['COU', '970', 2, 'Unidad de Valor Real', 'UVR', 'p', 10.2, 'americas', 'Colombia'],
  ['MXV', '979', 2, 'Mexican Unidad de Inversion (UDI)', 'UDI', 'p', 2.17, 'americas', 'Mexico'],
  ['USN', '997', 2, 'US Dollar (Next day)', 'USN', 'p', 1.0, 'americas', 'United States of America'],
  ['UYI', '940', 0, 'Uruguay Peso en Unidades Indexadas (UI)', 'UI', 'p', 6.27, 'americas', 'Uruguay'],
  ['UYW', '927', 4, 'Unidad Previsional', 'UP', 'p', 0.0245, 'americas', 'Uruguay'],
];

/** Precious metals (troy ounce). Operational precision: 4 decimals. */
const METALS: Row[] = [
  ['XAU', '959', null, 'Gold (troy ounce)', 'oz Au', 's', 0.000262, 'supranational', 'Precious metal'],
  ['XAG', '961', null, 'Silver (troy ounce)', 'oz Ag', 's', 0.0228, 'supranational', 'Precious metal'],
  ['XPT', '962', null, 'Platinum (troy ounce)', 'oz Pt', 's', 0.00064, 'supranational', 'Precious metal'],
  ['XPD', '964', null, 'Palladium (troy ounce)', 'oz Pd', 's', 0.00083, 'supranational', 'Precious metal'],
];

/** Special codes. */
const SPECIAL: Row[] = [
  ['XDR', '960', null, 'SDR (Special Drawing Right)', 'SDR', 's', 0.728, 'supranational', 'International Monetary Fund'],
  ['XSU', '994', null, 'Sucre', 'XSU', 's', null, 'supranational', 'ALBA (Sistema Unitario de Compensación Regional)'],
  ['XUA', '965', null, 'ADB Unit of Account', 'XUA', 's', 0.73, 'supranational', 'African Development Bank'],
  ['XBA', '955', null, 'Bond Markets Unit European Composite Unit (EURCO)', 'XBA', 's', null, 'supranational', 'Bond markets'],
  ['XBB', '956', null, 'Bond Markets Unit European Monetary Unit (E.M.U.-6)', 'XBB', 's', null, 'supranational', 'Bond markets'],
  ['XBC', '957', null, 'Bond Markets Unit European Unit of Account 9 (E.U.A.-9)', 'XBC', 's', null, 'supranational', 'Bond markets'],
  ['XBD', '958', null, 'Bond Markets Unit European Unit of Account 17 (E.U.A.-17)', 'XBD', 's', null, 'supranational', 'Bond markets'],
  ['XTS', '963', null, 'Code reserved for testing', 'XTS', 's', null, 'supranational', 'Testing'],
  ['XXX', '999', null, 'No currency', '¤', 's', null, 'supranational', 'Transactions where no currency is involved'],
];

/** Recently withdrawn codes kept for historical records. */
const WITHDRAWN: Row[] = [
  ['BGN', '975', 2, 'Bulgarian Lev', 'лв', 's', 1.676, 'europe', 'Bulgaria'],
  ['ANG', '532', 2, 'Netherlands Antillean Guilder', 'NAƒ', 'p', 1.79, 'americas', 'Curaçao|Sint Maarten'],
  ['ZWL', '932', 2, 'Zimbabwe Dollar', 'Z$', 'p', null, 'africa', 'Zimbabwe'],
  ['SLL', '694', 2, 'Leone (old)', 'Le', 'p', 22800, 'africa', 'Sierra Leone'],
  ['HRK', '191', 2, 'Kuna', 'kn', 's', 6.46, 'europe', 'Croatia'],
  ['CUC', '931', 2, 'Peso Convertible', 'CUC$', 'p', 1.0, 'americas', 'Cuba'],
  ['VEF', '937', 2, 'Bolívar Fuerte', 'Bs.F', 'p', null, 'americas', 'Venezuela'],
  ['MRO', '478', 2, 'Ouguiya (old)', 'UM', 's', 399, 'africa', 'Mauritania'],
  ['STD', '678', 2, 'Dobra (old)', 'Db', 's', 21000, 'africa', 'Sao Tome and Principe'],
];

const WITHDRAWN_META: Record<string, { year: number; replacedBy?: string }> = {
  BGN: { year: 2026, replacedBy: 'EUR' },
  ANG: { year: 2025, replacedBy: 'XCG' },
  ZWL: { year: 2024, replacedBy: 'ZWG' },
  SLL: { year: 2024, replacedBy: 'SLE' },
  HRK: { year: 2023, replacedBy: 'EUR' },
  CUC: { year: 2021, replacedBy: 'CUP' },
  VEF: { year: 2018, replacedBy: 'VES' },
  MRO: { year: 2018, replacedBy: 'MRU' },
  STD: { year: 2018, replacedBy: 'STN' },
};

function toDef(r: Row, kind: CurrencyDef['kind'], status: CurrencyDef['status']): CurrencyDef {
  const [code, numeric, isoMinor, name, symbol, pos, perUSD, region, countries] = r;
  return {
    code,
    numeric,
    name,
    symbol,
    isoMinor,
    decimals: isoMinor ?? 4,
    countries: countries.split('|'),
    kind,
    status,
    position: pos === 'p' ? 'prefix' : 'suffix',
    defaultPerUSD: perUSD,
    region,
  };
}

export const ISO_CURRENCIES: CurrencyDef[] = [
  ...FIAT.map((r) => toDef(r, 'fiat', 'active')),
  ...FUNDS.map((r) => toDef(r, 'fund', 'non_transactional')),
  ...METALS.map((r) => toDef(r, 'metal', 'active')),
  ...SPECIAL.map((r) => {
    const d = toDef(r, 'special', 'non_transactional');
    if (d.code === 'XDR') d.note = 'Quoted for reference; not used for client payments.';
    return d;
  }),
  ...WITHDRAWN.map((r) => {
    const d = toDef(r, 'fiat', 'withdrawn');
    d.withdrawnYear = WITHDRAWN_META[d.code].year;
    d.replacedBy = WITHDRAWN_META[d.code].replacedBy;
    return d;
  }),
];
