/**
 * Treasury-side client services: Tax Center (simulation — not tax advice),
 * Insurance (Wardstone Mutual, demo products), Dispute Center, KYC, and the
 * Deep Vaults (safe-deposit boxes).
 */
import { db } from '../db/db';
import { BankError } from '../errors';
import { nowISO, addMonths, addYears, todayKey } from '../clock';
import { uid, randomDigits } from '../util/random';
import { actor } from '../context';
import { can, requirePermission } from '../security/permissions';
import { hashSecret, newSalt, verifySecret } from '../util/crypto';
import { execute } from './engine';
import { availableOf } from './ledger';
import { canOperate, getAccountOrThrow, GL } from './accounts';
import { createDocument } from '../docs/documents';
import { audit } from '../ops/audit';
import { notify, sendMail } from '../comms/notify';
import type {
  Dispute, DisputeReason, DisputeStatus, InsuranceClaim, InsurancePolicy, InsuranceProduct, KycDocType, KycRecord, TaxRecord, Vault, VaultAccess,
} from '../types';

/* ═════════════ TAX CENTER (simulation) ═════════════ */

export const TAX_CALENDAR = [
  { month: 1, day: 31, key: 'tax.cal.property' },
  { month: 3, day: 31, key: 'tax.cal.declaration' },
  { month: 4, day: 15, key: 'tax.cal.q1' },
  { month: 7, day: 15, key: 'tax.cal.q2' },
  { month: 10, day: 15, key: 'tax.cal.q3' },
  { month: 12, day: 20, key: 'tax.cal.business' },
];

export async function payTax(id: string, fromAccountId: string) {
  const t = await db.taxes.get(id);
  if (!t) throw new BankError('NOT_FOUND');
  if (t.ownerId !== actor().userId && !actor().system) throw new BankError('PERMISSION_DENIED');
  if (t.status !== 'due' && t.status !== 'assessed') throw new BankError('INVALID_STATE', { status: t.status });
  const acc = await getAccountOrThrow(fromAccountId);
  if (!canOperate(acc)) throw new BankError('PERMISSION_DENIED');
  const owner = await db.users.get(t.ownerId);
  const tx = await execute({
    draft: {
      type: 'tax', amount: t.amount, currency: t.currency, fromAccountId: acc.id, sender: { name: owner?.name ?? 'Client', accountNumber: acc.number },
      recipient: { name: 'Revenue Office of Aldermoor' }, description: `${t.description} (${t.number})`, category: 'taxes', channel: 'app', refPrefix: 'TAX', meta: { taxId: t.id },
    },
    validate: async () => {
      const avail = await availableOf(acc.id, t.currency);
      if (avail < t.amount) throw new BankError('INSUFFICIENT_FUNDS', { available: avail, required: t.amount, currency: t.currency });
    },
    screen: false,
    plan: () => [{ memo: `Tax ${t.number}`, lines: [{ accountId: acc.id, currency: t.currency, side: 'D', amount: t.amount }, { accountId: GL.TAX, currency: t.currency, side: 'C', amount: t.amount }] }],
  });
  const doc = await createDocument({
    type: 'tax', title: 'Tax Payment Receipt', ownerId: t.ownerId, data: { taxId: t.id, number: t.number, kind: t.kind, year: t.year, amount: t.amount, currency: t.currency, description: t.description, paidAt: nowISO(), txId: tx.id, payer: owner?.name },
    links: { txIds: [tx.id], accountIds: [acc.id] }, authorName: 'Revenue Office of Aldermoor', authorId: 'BANK', silent: true,
  });
  await db.taxes.update(id, { status: 'paid', paidAt: nowISO(), txId: tx.id, documentId: doc.id });
  return tx;
}

export async function generateTaxStatement(year: number) {
  const a = actor();
  const records = await db.taxes.where('ownerId').equals(a.userId).filter((t) => t.year === year).toArray();
  const owner = await db.users.get(a.userId);
  const interestTx = await db.transactions.where('partyIds').equals(a.userId).filter((t) => (t.type === 'deposit_interest' || t.type === 'dividend') && t.createdAt.startsWith(String(year))).toArray();
  return createDocument({
    type: 'tax', title: `Annual Tax Statement ${year}`, ownerId: a.userId,
    data: { kind: 'annual', year, taxpayer: owner?.name, clientId: owner?.clientId, records: records.map((r) => ({ number: r.number, kind: r.kind, amount: r.amount, currency: r.currency, status: r.status })), income: interestTx.map((t) => ({ ref: t.ref, type: t.type, amount: t.amount, currency: t.currency, at: t.createdAt })) },
    body: ['This statement is generated by a simulation of the Revenue Office of Aldermoor for demonstration purposes only. It is not tax advice.'],
    authorName: 'Revenue Office of Aldermoor', authorId: 'BANK',
  });
}

export async function fileDeclaration(year: number, declaredIncome: number, currency: string) {
  const a = actor();
  if (!(declaredIncome >= 0)) throw new BankError('INVALID_AMOUNT');
  // Simulated flat rate for the fictional realm; not a real tax computation.
  const tax = Math.round(declaredIncome * 0.12);
  const rec: TaxRecord = {
    id: uid('TAXR'), number: `DCL-${year}-${randomDigits(5)}`, ownerId: a.userId, year, kind: 'declaration', amount: tax, currency, status: 'assessed',
    dueDate: `${year + 1}-04-15`, description: `Income declaration ${year} (simulated 12% flat assessment)`,
  };
  await db.taxes.add(rec);
  await audit({ action: 'tax.declare', object: 'tax', objectId: rec.id, details: `${declaredIncome} ${currency}` });
  await sendMail(a.userId, 'tax_notice', { number: rec.number, amt: tax, ccy: currency, due: rec.dueDate });
  return rec;
}

/* ═════════════ INSURANCE (Wardstone Mutual — demo) ═════════════ */

export const INSURANCE_PRODUCTS: Record<InsuranceProduct, { coverage: number; premiumMonthly: number; premiumYearly: number }> = {
  home: { coverage: 250_000_00, premiumMonthly: 18_50, premiumYearly: 199_00 },
  travel: { coverage: 50_000_00, premiumMonthly: 6_90, premiumYearly: 69_00 },
  device: { coverage: 3_000_00, premiumMonthly: 4_20, premiumYearly: 45_00 },
  business: { coverage: 1_000_000_00, premiumMonthly: 85_00, premiumYearly: 920_00 },
  life: { coverage: 500_000_00, premiumMonthly: 29_00, premiumYearly: 310_00 },
};

async function chargePremium(p: InsurancePolicy) {
  const acc = await getAccountOrThrow(p.accountId);
  const owner = await db.users.get(p.ownerId);
  return execute({
    draft: {
      type: 'insurance', amount: p.premium, currency: p.currency, fromAccountId: acc.id, sender: { name: owner?.name ?? 'Client', accountNumber: acc.number },
      recipient: { name: 'Wardstone Mutual' }, description: `Premium ${p.number} (${p.product})`, category: 'insurance', channel: 'app', refPrefix: 'INS', meta: { policyId: p.id }, initiatorId: p.ownerId,
    },
    validate: async () => {
      const avail = await availableOf(acc.id, p.currency);
      if (avail < p.premium) throw new BankError('INSUFFICIENT_FUNDS', { available: avail, required: p.premium, currency: p.currency });
    },
    screen: false,
    plan: () => [{ memo: `Premium ${p.number}`, lines: [{ accountId: acc.id, currency: p.currency, side: 'D', amount: p.premium }, { accountId: GL.INSURANCE, currency: p.currency, side: 'C', amount: p.premium }] }],
  });
}

export async function buyPolicy(product: InsuranceProduct, period: 'monthly' | 'yearly', accountId: string, insured: string) {
  const acc = await getAccountOrThrow(accountId);
  if (!canOperate(acc)) throw new BankError('PERMISSION_DENIED');
  if (acc.currency !== 'CRWN' && !acc.pockets.includes('CRWN')) throw new BankError('CURRENCY_UNSUPPORTED', { currency: acc.currency, required: 'CRWN' });
  const def = INSURANCE_PRODUCTS[product];
  const start = todayKey();
  const p: InsurancePolicy = {
    id: uid('POLY'), number: `WM-${product.slice(0, 2).toUpperCase()}-${randomDigits(6)}`, ownerId: acc.ownerId, product, insured: insured || product,
    coverage: def.coverage, premium: period === 'monthly' ? def.premiumMonthly : def.premiumYearly, currency: 'CRWN', period,
    startDate: start, endDate: addYears(start, 1).toISOString().slice(0, 10),
    nextPremium: (period === 'monthly' ? addMonths(start, 1) : addYears(start, 1)).toISOString().slice(0, 10),
    status: 'active', accountId: acc.id, createdAt: nowISO(),
  };
  await chargePremium(p);
  const owner = await db.users.get(acc.ownerId);
  const doc = await createDocument({
    type: 'policy', title: 'Insurance Policy', ownerId: acc.ownerId,
    data: { policyId: p.id, number: p.number, product, insured: p.insured, coverage: p.coverage, premium: p.premium, currency: p.currency, period, startDate: p.startDate, endDate: p.endDate, holder: owner?.name, insurer: 'Wardstone Mutual (demonstration product)' },
    authorName: 'Wardstone Mutual', authorId: 'BANK', expiresAt: p.endDate + 'T23:59:59.000Z',
  });
  p.documentId = doc.id;
  await db.policies.add(p);
  await audit({ action: 'insurance.buy', object: 'policy', objectId: p.id, details: `${product} ${period}` });
  await sendMail(acc.ownerId, 'policy_issued', { number: p.number, product }, doc.id);
  return p;
}

export async function payPremium(id: string) {
  const p = await db.policies.get(id);
  if (!p) throw new BankError('NOT_FOUND');
  if (p.ownerId !== actor().userId && !actor().system) throw new BankError('PERMISSION_DENIED');
  if (!['active', 'lapsed'].includes(p.status)) throw new BankError('INVALID_STATE', { status: p.status });
  const tx = await chargePremium(p);
  const next = (p.period === 'monthly' ? addMonths(p.nextPremium, 1) : addYears(p.nextPremium, 1)).toISOString().slice(0, 10);
  await db.policies.update(id, { nextPremium: next, status: 'active' });
  return tx;
}

export async function renewPolicy(id: string) {
  const p = await db.policies.get(id);
  if (!p) throw new BankError('NOT_FOUND');
  if (p.ownerId !== actor().userId && !actor().system) throw new BankError('PERMISSION_DENIED');
  if (p.status === 'cancelled') throw new BankError('INVALID_STATE', { status: p.status });
  await chargePremium(p);
  const end = addYears(p.endDate > todayKey() ? p.endDate : todayKey(), 1).toISOString().slice(0, 10);
  await db.policies.update(id, { endDate: end, status: 'active' });
  if (p.documentId) await db.documents.update(p.documentId, { expiresAt: end + 'T23:59:59.000Z' });
  await audit({ action: 'insurance.renew', object: 'policy', objectId: id, details: end });
}

export async function cancelPolicy(id: string) {
  const p = await db.policies.get(id);
  if (!p || (p.ownerId !== actor().userId && !actor().system)) throw new BankError('PERMISSION_DENIED');
  await db.policies.update(id, { status: 'cancelled' });
  await audit({ action: 'insurance.cancel', object: 'policy', objectId: id });
}

export async function fileClaim(policyId: string, description: string, amount: number) {
  const p = await db.policies.get(policyId);
  if (!p) throw new BankError('NOT_FOUND');
  if (p.ownerId !== actor().userId) throw new BankError('PERMISSION_DENIED');
  if (p.status !== 'active') throw new BankError('INVALID_STATE', { status: p.status });
  if (!(amount > 0) || amount > p.coverage) throw new BankError('INVALID_AMOUNT');
  if (!description.trim()) throw new BankError('VALIDATION', { field: 'description' });
  const c: InsuranceClaim = {
    id: uid('CLM'), number: `CL-${randomDigits(7)}`, policyId, ownerId: p.ownerId, description, amount, currency: p.currency, status: 'submitted',
    createdAt: nowISO(), timeline: [{ step: 'submitted', at: nowISO(), ok: true, actor: actor().name }],
  };
  await db.claims.add(c);
  await audit({ action: 'insurance.claim', object: 'claim', objectId: c.id, details: `${amount} ${p.currency}` });
  return c;
}

export async function decideClaim(id: string, decision: 'under_review' | 'approved' | 'denied' | 'paid') {
  requirePermission('claims.review');
  const c = await db.claims.get(id);
  if (!c) throw new BankError('NOT_FOUND');
  const p = await db.policies.get(c.policyId);
  if (!p) throw new BankError('NOT_FOUND');
  let payoutTxId: string | undefined;
  if (decision === 'paid') {
    if (c.status !== 'approved') throw new BankError('INVALID_STATE', { status: c.status });
    const acc = await getAccountOrThrow(p.accountId);
    const tx = await execute({
      draft: { type: 'claim', amount: c.amount, currency: c.currency, toAccountId: acc.id, sender: { name: 'Wardstone Mutual' }, recipient: { name: acc.name, accountNumber: acc.number }, description: `Claim payout ${c.number}`, category: 'insurance', channel: 'system', refPrefix: 'INS', partyIds: [c.ownerId] },
      screen: false,
      plan: () => [{ memo: `Claim ${c.number}`, allowOverdraft: true, lines: [{ accountId: GL.INSURANCE, currency: c.currency, side: 'D', amount: c.amount }, { accountId: acc.id, currency: c.currency, side: 'C', amount: c.amount }] }],
    });
    payoutTxId = tx.id;
  }
  await db.claims.update(id, { status: decision, payoutTxId, timeline: [...c.timeline, { step: decision === 'denied' ? 'rejected' : decision === 'paid' ? 'completed' : decision === 'approved' ? 'approved' : 'review', at: nowISO(), ok: decision !== 'denied', actor: actor().name }] });
  await audit({ action: `insurance.claim_${decision}`, object: 'claim', objectId: id, txId: payoutTxId });
  await notify(c.ownerId, { category: 'system', titleKey: 'n.claim.update.title', bodyKey: 'n.claim.update.body', params: { number: c.number, status: decision }, link: '/insurance' });
  await sendMail(c.ownerId, 'claim_update', { number: c.number, status: decision });
}

export async function processPolicies(dayKey: string) {
  const active = await db.policies.where('status').equals('active').toArray();
  for (const p of active) {
    if (p.endDate < dayKey) {
      await db.policies.update(p.id, { status: 'expired' });
      continue;
    }
    if (p.nextPremium <= dayKey) {
      try {
        await chargePremium(p);
        const next = (p.period === 'monthly' ? addMonths(p.nextPremium, 1) : addYears(p.nextPremium, 1)).toISOString().slice(0, 10);
        await db.policies.update(p.id, { nextPremium: next });
      } catch {
        await db.policies.update(p.id, { status: 'lapsed' });
        await notify(p.ownerId, { category: 'system', titleKey: 'n.policy.lapsed.title', bodyKey: 'n.policy.lapsed.body', params: { number: p.number }, link: '/insurance', priority: 'high' });
      }
    }
  }
}

/* ═════════════ DISPUTES ═════════════ */

export async function openDispute(txId: string, reason: DisputeReason, description: string) {
  const tx = await db.transactions.get(txId);
  if (!tx) throw new BankError('NOT_FOUND', { object: 'transaction' });
  const a = actor();
  if (!tx.partyIds.includes(a.userId)) throw new BankError('PERMISSION_DENIED');
  if (tx.status !== 'completed') throw new BankError('INVALID_STATE', { status: tx.status });
  const open = await db.disputes.where('txId').equals(txId).filter((d) => !['resolved', 'rejected', 'refunded'].includes(d.status)).count();
  if (open) throw new BankError('INVALID_STATE', { reason: 'dispute already open' });
  const d: Dispute = {
    id: uid('DSP'), number: `DS-${randomDigits(7)}`, ownerId: a.userId, txId, reason, description, amount: tx.amount + tx.fee, currency: tx.currency,
    status: 'opened', createdAt: nowISO(), updatedAt: nowISO(), timeline: [{ status: 'opened', at: nowISO(), by: a.name }], evidence: [],
  };
  await db.disputes.add(d);
  await audit({ action: 'dispute.open', object: 'dispute', objectId: d.id, txId, details: reason });
  await notify(a.userId, { category: 'payments', titleKey: 'n.dispute.opened.title', bodyKey: 'n.dispute.opened.body', params: { number: d.number, ref: tx.ref }, link: `/disputes/${d.id}` });
  return d;
}

export async function addDisputeEvidence(id: string, text: string) {
  const d = await db.disputes.get(id);
  if (!d) throw new BankError('NOT_FOUND');
  const a = actor();
  if (d.ownerId !== a.userId && !can('disputes.review')) throw new BankError('PERMISSION_DENIED');
  if (!text.trim()) throw new BankError('VALIDATION', { field: 'evidence' });
  const status: DisputeStatus = d.status === 'evidence_required' && d.ownerId === a.userId ? 'under_review' : d.status;
  await db.disputes.update(id, {
    evidence: [...d.evidence, { at: nowISO(), by: a.name, text }], status, updatedAt: nowISO(),
    timeline: status !== d.status ? [...d.timeline, { status, at: nowISO(), by: a.name, note: 'evidence submitted' }] : d.timeline,
  });
  await audit({ action: 'dispute.evidence', object: 'dispute', objectId: id });
}

export async function setDisputeStatus(id: string, status: DisputeStatus, note = '') {
  requirePermission('disputes.review');
  const d = await db.disputes.get(id);
  if (!d) throw new BankError('NOT_FOUND');
  if (['resolved', 'rejected', 'refunded'].includes(d.status)) throw new BankError('INVALID_STATE', { status: d.status });
  let refundTxId: string | undefined;
  if (status === 'refunded') {
    const tx = await db.transactions.get(d.txId);
    if (!tx) throw new BankError('NOT_FOUND');
    const target = tx.fromAccountId ?? tx.toAccountId;
    if (!target) throw new BankError('INVALID_ACCOUNT');
    const acc = await getAccountOrThrow(target);
    const ccy = acc.pockets.includes(d.currency) ? d.currency : acc.currency;
    const refund = await execute({
      draft: {
        type: 'refund', amount: d.amount, currency: ccy, toAccountId: acc.id, sender: { name: 'Disputes & Chargebacks' }, recipient: { name: acc.name, accountNumber: acc.number },
        description: `Refund for dispute ${d.number} (${tx.ref})`, category: 'transfers', channel: 'system', refPrefix: 'RFD', relatedTxIds: [tx.id], partyIds: [d.ownerId],
      },
      screen: false,
      plan: () => [{ memo: `Dispute refund ${d.number}`, allowOverdraft: true, lines: [{ accountId: GL.DISPUTES, currency: ccy, side: 'D', amount: d.amount }, { accountId: acc.id, currency: ccy, side: 'C', amount: d.amount }] }],
    });
    refundTxId = refund.id;
    await db.transactions.update(tx.id, { relatedTxIds: [...tx.relatedTxIds, refund.id] });
  }
  await db.disputes.update(id, { status, refundTxId, updatedAt: nowISO(), timeline: [...d.timeline, { status, at: nowISO(), by: actor().name, note }] });
  await audit({ action: `dispute.${status}`, object: 'dispute', objectId: id, txId: refundTxId, details: note });
  await notify(d.ownerId, { category: 'payments', titleKey: 'n.dispute.update.title', bodyKey: 'n.dispute.update.body', params: { number: d.number, status }, link: `/disputes/${id}`, priority: status === 'evidence_required' ? 'high' : 'normal' });
  await sendMail(d.ownerId, 'dispute_update', { number: d.number, status, note });
}

/* ═════════════ KYC ═════════════ */

export async function submitKyc(input: { docType: KycDocType; docNumber: string; issuedBy: string; issueDate: string; expiryDate: string; fileName?: string; fileData?: string }) {
  const a = actor();
  if (!input.docNumber.trim()) throw new BankError('VALIDATION', { field: 'docNumber' });
  if (input.expiryDate <= todayKey()) throw new BankError('DOCUMENT_EXPIRED');
  const rec: KycRecord = { id: uid('KYC'), userId: a.userId, ...input, docNumber: input.docNumber.trim().toUpperCase(), status: 'pending', submittedAt: nowISO() };
  await db.kyc.add(rec);
  const user = await db.users.get(a.userId);
  if (user && user.kycStatus !== 'verified') await db.users.update(a.userId, { kycStatus: 'pending' });
  await audit({ action: 'kyc.submit', object: 'kyc', objectId: rec.id, details: input.docType });
  return rec;
}

export async function reviewKyc(id: string, approve: boolean, reason = '') {
  requirePermission('kyc.review');
  const rec = await db.kyc.get(id);
  if (!rec) throw new BankError('NOT_FOUND');
  if (rec.status !== 'pending') throw new BankError('INVALID_STATE', { status: rec.status });
  await db.kyc.update(id, { status: approve ? 'verified' : 'rejected', reviewedAt: nowISO(), reviewedBy: actor().name, reason });
  const all = await db.kyc.where('userId').equals(rec.userId).toArray();
  const userStatus = all.some((k) => (k.id === id ? approve : k.status === 'verified')) ? 'verified' : approve ? 'verified' : all.some((k) => k.status === 'pending' && k.id !== id) ? 'pending' : 'rejected';
  await db.users.update(rec.userId, { kycStatus: userStatus });
  await audit({ action: approve ? 'kyc.verify' : 'kyc.reject', object: 'kyc', objectId: id, details: reason });
  await notify(rec.userId, { category: 'security', titleKey: approve ? 'n.kyc.verified.title' : 'n.kyc.rejected.title', bodyKey: approve ? 'n.kyc.verified.body' : 'n.kyc.rejected.body', params: { reason }, link: '/kyc', priority: 'high' });
  await sendMail(rec.userId, approve ? 'kyc_verified' : 'kyc_rejected', { reason });
}

export async function expireKyc(dayKey: string) {
  const verified = (await db.kyc.where('status').equals('verified').toArray()).filter((k) => k.expiryDate < dayKey);
  for (const k of verified) {
    await db.kyc.update(k.id, { status: 'expired' });
    const others = await db.kyc.where('userId').equals(k.userId).filter((x) => x.id !== k.id && x.status === 'verified').count();
    if (!others) await db.users.update(k.userId, { kycStatus: 'expired' });
    await notify(k.userId, { category: 'security', titleKey: 'n.kyc.expired.title', bodyKey: 'n.kyc.expired.body', params: {}, link: '/kyc', priority: 'high' });
  }
  return verified.length;
}

/* ═════════════ DEEP VAULTS ═════════════ */

export const VAULT_LEVELS: Record<number, { name: string; fee: number; wards: string[] }> = {
  1: { name: 'Bronze Ward', fee: 12_00, wards: ['Brass lock'] },
  2: { name: 'Silver Ward', fee: 28_00, wards: ['Brass lock', 'Combination dial'] },
  3: { name: 'Gold Ward', fee: 55_00, wards: ['Brass lock', 'Combination dial', 'Warden escort'] },
  4: { name: 'Obsidian Ward', fee: 120_00, wards: ['Combination dial', 'Warden escort', 'Rune seal'] },
  5: { name: 'Sovereign Ward', fee: 400_00, wards: ['Combination dial', 'Two wardens', 'Rune seal', 'Blood-oath register'] },
};

async function logVault(vault: Vault, action: VaultAccess['action'], result: VaultAccess['result'], note?: string) {
  const a = actor();
  await db.vaultAccess.add({ id: uid('VAC'), vaultId: vault.id, at: nowISO(), userId: a.userId, userName: a.name, action, result, note });
  await audit({ action: `vault.${action}`, object: 'vault', objectId: vault.id, result, details: note });
}

async function vaultFor(id: string) {
  const v = await db.vaults.get(id);
  if (!v) throw new BankError('NOT_FOUND', { object: 'vault' });
  const a = actor();
  if (v.ownerId !== a.userId && !can('vaults.manage') && !a.system) throw new BankError('PERMISSION_DENIED');
  return v;
}

export async function rentVault(level: Vault['level'], size: Vault['size'], branchId: string, combination: string, accountId: string) {
  const a = actor();
  if (!/^\d{4,8}$/.test(combination)) throw new BankError('VALIDATION', { field: 'combination' });
  const acc = await getAccountOrThrow(accountId);
  if (!canOperate(acc)) throw new BankError('PERMISSION_DENIED');
  const fee = VAULT_LEVELS[level].fee * ({ S: 1, M: 1.5, L: 2.2, XL: 3.5 } as const)[size];
  const user = await db.users.get(acc.ownerId);
  await execute({
    draft: { type: 'vault', amount: Math.round(fee), currency: 'CRWN', fromAccountId: acc.id, sender: { name: user?.name ?? a.name, accountNumber: acc.number }, recipient: { name: 'Wardens of the Deep Vaults' }, description: `Vault rental (${VAULT_LEVELS[level].name}, ${size})`, category: 'bills', channel: 'app', refPrefix: 'VLT' },
    validate: async () => {
      const avail = await availableOf(acc.id, 'CRWN');
      if (avail < fee) throw new BankError('INSUFFICIENT_FUNDS', { available: avail, required: Math.round(fee), currency: 'CRWN' });
    },
    screen: false,
    plan: () => [{ memo: 'Vault rent', lines: [{ accountId: acc.id, currency: 'CRWN', side: 'D', amount: Math.round(fee) }, { accountId: GL.FEES, currency: 'CRWN', side: 'C', amount: Math.round(fee) }] }],
  });
  const salt = newSalt();
  const v: Vault = {
    id: uid('VLT'), number: `UV-${String(level)}${randomDigits(4)}`, ownerId: acc.ownerId, ownerName: user?.name ?? a.name, level, size, branchId, status: 'sealed',
    contents: [], rentFee: Math.round(fee), rentCurrency: 'CRWN', accountId: acc.id, combinationHash: await hashSecret(combination, salt), combinationSalt: salt,
    failedAttempts: 0, createdAt: nowISO(), wards: VAULT_LEVELS[level].wards,
  };
  await db.vaults.add(v);
  await logVault(v, 'rent', 'success', `${VAULT_LEVELS[level].name} ${size}`);
  return v;
}

export async function openVault(id: string, combination: string) {
  const v = await vaultFor(id);
  if (v.status === 'locked') throw new BankError('ACCOUNT_FROZEN', { vault: v.number });
  if (v.status === 'audit') throw new BankError('INVALID_STATE', { status: v.status });
  const ok = await verifySecret(combination, v.combinationSalt, v.combinationHash);
  if (!ok) {
    const attempts = v.failedAttempts + 1;
    await db.vaults.update(id, { failedAttempts: attempts, status: attempts >= 3 ? 'locked' : v.status });
    await logVault(v, 'failed_attempt', 'failure', `attempt ${attempts}`);
    if (attempts >= 3) {
      await notify(v.ownerId, { category: 'security', titleKey: 'n.vault.locked.title', bodyKey: 'n.vault.locked.body', params: { number: v.number }, link: `/vaults`, priority: 'high' });
      await sendMail(v.ownerId, 'vault_access', { number: v.number, event: 'locked' });
    }
    throw new BankError('VERIFICATION_FAILED', { attemptsLeft: Math.max(0, 3 - attempts) });
  }
  await db.vaults.update(id, { status: 'open', failedAttempts: 0 });
  await logVault(v, 'open', 'success');
  await notify(v.ownerId, { category: 'security', titleKey: 'n.vault.opened.title', bodyKey: 'n.vault.opened.body', params: { number: v.number }, link: '/vaults' });
}

export async function closeVault(id: string) {
  const v = await vaultFor(id);
  if (v.status !== 'open') throw new BankError('INVALID_STATE', { status: v.status });
  await db.vaults.update(id, { status: 'sealed' });
  await logVault(v, 'close', 'success');
}

export async function depositVaultItem(id: string, item: string, description: string, value?: number, currency?: string) {
  const v = await vaultFor(id);
  if (v.status !== 'open') throw new BankError('INVALID_STATE', { status: v.status });
  if (!item.trim()) throw new BankError('VALIDATION', { field: 'item' });
  await db.vaults.update(id, { contents: [...v.contents, { id: uid('VI', 6), item: item.trim(), description, value, currency, addedAt: nowISO() }] });
  await logVault(v, 'deposit_item', 'success', item);
}

export async function withdrawVaultItem(id: string, itemId: string) {
  const v = await vaultFor(id);
  if (v.status !== 'open') throw new BankError('INVALID_STATE', { status: v.status });
  const it = v.contents.find((c) => c.id === itemId);
  if (!it) throw new BankError('NOT_FOUND');
  await db.vaults.update(id, { contents: v.contents.filter((c) => c.id !== itemId) });
  await logVault(v, 'withdraw_item', 'success', it.item);
}

export async function unlockVault(id: string, newCombination?: string) {
  requirePermission('vaults.manage');
  const v = await vaultFor(id);
  const patch: Partial<Vault> = { status: 'sealed', failedAttempts: 0 };
  if (newCombination) {
    const salt = newSalt();
    patch.combinationHash = await hashSecret(newCombination, salt);
    patch.combinationSalt = salt;
  }
  await db.vaults.update(id, patch);
  await logVault(v, 'unlock', 'success');
}

export async function auditVault(id: string, start: boolean) {
  requirePermission('vaults.manage');
  const v = await vaultFor(id);
  await db.vaults.update(id, { status: start ? 'audit' : 'sealed' });
  await logVault(v, start ? 'audit' : 'close', 'success', start ? 'audit started' : 'audit finished');
}
