/** Route table with lazily loaded feature pages (each module is its own chunk). */
import type { ComponentType } from 'react';

type Loader = () => Promise<{ default: ComponentType }>;

export const ROUTES: { path: string; load: Loader }[] = [
  { path: '/', load: () => import('@/features/dashboard/DashboardPage') },
  { path: '/accounts', load: () => import('@/features/accounts/AccountsPage') },
  { path: '/accounts/:id', load: () => import('@/features/accounts/AccountDetailPage') },
  { path: '/transactions', load: () => import('@/features/transactions/TransactionsPage') },
  { path: '/transactions/:id', load: () => import('@/features/transactions/TransactionDetailPage') },
  { path: '/payments', load: () => import('@/features/payments/PaymentsPage') },
  { path: '/pay/:code', load: () => import('@/features/payments/PayLinkPage') },
  { path: '/international', load: () => import('@/features/international/InternationalPage') },
  { path: '/exchange', load: () => import('@/features/exchange/ExchangePage') },
  { path: '/currencies', load: () => import('@/features/currencies/CurrenciesPage') },
  { path: '/qr', load: () => import('@/features/qr/QrPage') },
  { path: '/cards', load: () => import('@/features/cards/CardsPage') },
  { path: '/cards/:id', load: () => import('@/features/cards/CardDetailPage') },
  { path: '/atm', load: () => import('@/features/atm/AtmPage') },
  { path: '/teller', load: () => import('@/features/teller/TellerPage') },
  { path: '/checks', load: () => import('@/features/checks/ChecksPage') },
  { path: '/checks/:id', load: () => import('@/features/checks/CheckDetailPage') },
  { path: '/seals', load: () => import('@/features/seals/SealsPage') },
  { path: '/documents', load: () => import('@/features/documents/DocumentsPage') },
  { path: '/documents/:id', load: () => import('@/features/documents/DocumentDetailPage') },
  { path: '/editor', load: () => import('@/features/editor/EditorPage') },
  { path: '/editor/:id', load: () => import('@/features/editor/EditorPage') },
  { path: '/verify', load: () => import('@/features/verify/VerifyPage') },
  { path: '/deposits', load: () => import('@/features/deposits/DepositsPage') },
  { path: '/deposits/:id', load: () => import('@/features/deposits/DepositDetailPage') },
  { path: '/loans', load: () => import('@/features/loans/LoansPage') },
  { path: '/loans/:id', load: () => import('@/features/loans/LoanDetailPage') },
  { path: '/credit', load: () => import('@/features/credit/CreditPage') },
  { path: '/investments', load: () => import('@/features/investments/InvestmentsPage') },
  { path: '/budget', load: () => import('@/features/budget/BudgetPage') },
  { path: '/recurring', load: () => import('@/features/recurring/RecurringPage') },
  { path: '/invoices', load: () => import('@/features/invoices/InvoicesPage') },
  { path: '/invoices/:id', load: () => import('@/features/invoices/InvoiceDetailPage') },
  { path: '/subscriptions', load: () => import('@/features/subscriptions/SubscriptionsPage') },
  { path: '/family', load: () => import('@/features/family/FamilyPage') },
  { path: '/business', load: () => import('@/features/business/BusinessPage') },
  { path: '/tax', load: () => import('@/features/tax/TaxPage') },
  { path: '/insurance', load: () => import('@/features/insurance/InsurancePage') },
  { path: '/disputes', load: () => import('@/features/disputes/DisputesPage') },
  { path: '/disputes/:id', load: () => import('@/features/disputes/DisputeDetailPage') },
  { path: '/fraud', load: () => import('@/features/fraud/FraudPage') },
  { path: '/kyc', load: () => import('@/features/kyc/KycPage') },
  { path: '/notifications', load: () => import('@/features/notifications/NotificationsPage') },
  { path: '/mailbox', load: () => import('@/features/mailbox/MailboxPage') },
  { path: '/messages', load: () => import('@/features/messages/MessagesPage') },
  { path: '/branches', load: () => import('@/features/branches/BranchesPage') },
  { path: '/employees', load: () => import('@/features/employees/EmployeesPage') },
  { path: '/archive', load: () => import('@/features/archive/ArchivePage') },
  { path: '/vaults', load: () => import('@/features/vaults/VaultsPage') },
  { path: '/audit', load: () => import('@/features/audit/AuditPage') },
  { path: '/admin', load: () => import('@/features/admin/AdminPage') },
  { path: '/analytics', load: () => import('@/features/analytics/AnalyticsPage') },
  { path: '/calendar', load: () => import('@/features/calendar/CalendarPage') },
  { path: '/security', load: () => import('@/features/security/SecurityPage') },
  { path: '/profile', load: () => import('@/features/profile/ProfilePage') },
  { path: '/status', load: () => import('@/features/status/StatusPage') },
  { path: '/cash', load: () => import('@/features/cash/CashPage') },
  { path: '/settings', load: () => import('@/features/settings/SettingsPage') },
  { path: '*', load: () => import('@/features/NotFoundPage') },
];
