/**
 * Forge the demo world through the real services (Node + in-memory IndexedDB)
 * and write it as a compressed snapshot module: src/data/demoWorld.ts
 * Usage: npm run snapshot
 */
import 'fake-indexeddb/auto';
import { gzipSync } from 'node:zlib';
import { writeFileSync, mkdirSync } from 'node:fs';
import { openDatabase } from '../src/core/db/db';
import { loadCaches } from '../src/core/boot';
import { seedDemo } from '../src/core/seed/seed';
import { exportSnapshot } from '../src/core/seed/snapshot';
import { reconcileBalances, trialBalance } from '../src/core/banking/ledger';
import { verifyAuditChain } from '../src/core/ops/audit';

const t = Date.now();
await openDatabase();
await loadCaches();
let last = -1;
const { warnings, anchorDay } = await seedDemo((p, l) => {
  if (p - last >= 10 || p === 100) {
    console.log(`  ${p}% ${l}`);
    last = p;
  }
});
const tb = await trialBalance();
if (tb.some((r) => r.debit !== r.credit)) throw new Error('Trial balance does not balance');
const rec = await reconcileBalances();
if (rec.drift.length) throw new Error('Balance projection drift');
const chain = await verifyAuditChain();
if (!chain.ok) throw new Error('Audit chain broken');
const snap = await exportSnapshot(anchorDay);
const json = JSON.stringify(snap);
const gz = gzipSync(Buffer.from(json), { level: 9 });
mkdirSync('src/data', { recursive: true });
writeFileSync(
  'src/data/demoWorld.ts',
  `/* Generated by scripts/build-snapshot.ts — fictional demo world (gzip + base64). Do not edit. */\nconst DEMO_WORLD = '${gz.toString('base64')}';\nexport default DEMO_WORLD;\n`,
);
const rows = Object.fromEntries(Object.entries(snap.tables).map(([k, v]) => [k, v.length]));
console.log(JSON.stringify(rows));
console.log(`snapshot: ${(json.length / 1e6).toFixed(2)} MB raw, ${(gz.length / 1e6).toFixed(2)} MB gzip, warnings ${warnings.length}, ${Math.round((Date.now() - t) / 1000)}s`);
for (const w of warnings) console.log('  warn:', w);
process.exit(0);
